import type { FastifyInstance } from 'fastify'; import { pool } from '../db/pool.js';
const ANALYZER_URL=process.env.ANALYZER_URL??'http://analyzer:7000'; const MAX=128*1024*1024;
export default async function video(app:FastifyInstance):Promise<void>{
 app.get('/fingerprints',{preHandler:[app.requirePerms('video:read')]},async()=>({data:(await pool.query(`SELECT id,sha256,md5,size_bytes,duration_ms,width,height,fps,codec,encoder,creation_time,gps,file_type,perceptual_frame_hashes,status,summary,created_at FROM aegis.video_fingerprints ORDER BY created_at DESC LIMIT 100`)).rows}));
 app.get('/fingerprints/:id',{preHandler:[app.requirePerms('video:read')]},async(req,reply)=>{const id=(req.params as {id:string}).id;const f=(await pool.query(`SELECT id,sha256,md5,size_bytes,duration_ms,width,height,fps,codec,encoder,creation_time,gps,file_type,perceptual_frame_hashes,status,summary,created_at FROM aegis.video_fingerprints WHERE id=$1`,[id])).rows[0];if(!f)return reply.code(404).send({error:'not_found'});return{...f,sightings:(await pool.query(`SELECT s.id,s.source_id,v.name source,s.url,s.author,s.snippet,s.observed_at,s.matched_via,s.confidence,s.status FROM aegis.video_sightings s JOIN aegis.video_sources v ON v.id=s.source_id WHERE s.fingerprint_id=$1 ORDER BY s.observed_at`,[id])).rows};});
 app.post('/fingerprints',{preHandler:[app.requirePerms('video:run')]},async(req,reply)=>{const file=await(req as any).file({limits:{fileSize:MAX}});if(!file)return reply.code(400).send({error:'no_file'});let bytes:Buffer;try{bytes=await file.toBuffer()}catch{return reply.code(413).send({error:'file_too_large'})}if(file.file.truncated)return reply.code(413).send({error:'file_too_large'});const res=await fetch(`${ANALYZER_URL}/analyze/video`,{method:'POST',headers:{'content-type':'application/octet-stream'},body:new Uint8Array(bytes)});if(!res.ok)return reply.code(502).send({error:'analyzer_error'});const r:any=await res.json();return(await pool.query(`INSERT INTO aegis.video_fingerprints(sha256,md5,size_bytes,duration_ms,width,height,fps,codec,encoder,creation_time,gps,file_type,perceptual_frame_hashes,summary,requested_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(sha256) DO UPDATE SET updated_at=now() RETURNING id,sha256`,[r.sha256,r.md5,r.size_bytes,r.duration_ms,r.width,r.height,r.fps,r.codec,r.encoder,r.creation_time,r.gps,r.file_type,r.perceptual_frame_hashes,r.summary,req.user.sub])).rows[0]});
 app.get('/sources',{preHandler:[app.requirePerms('video:read')]},async()=>({data:(await pool.query(`SELECT id,name,kind,enabled,poll_interval_secs,last_polled_at,health,created_at FROM aegis.video_sources ORDER BY name`)).rows}));
 app.post('/sources',{preHandler:[app.requirePerms('video:run')]},async(req,reply)=>{const b=req.body as any;if(!['telegram','x','facebook','snapchat','manual'].includes(b.kind))return reply.code(400).send({error:'bad_kind'});if(b.kind!=='telegram'&&b.kind!=='manual'&&b.enabled)return reply.code(400).send({error:'source_not_automatable'});return reply.code(201).send((await pool.query(`INSERT INTO aegis.video_sources(name,kind,config,enabled,poll_interval_secs) VALUES($1,$2,$3,$4,$5) RETURNING id,name,kind,enabled,poll_interval_secs,health`,[b.name,b.kind,JSON.stringify(b.config??{}),b.enabled??false,b.pollIntervalSecs??900])).rows[0])});
 app.patch('/sources/:id',{preHandler:[app.requirePerms('video:run')]},async(req,reply)=>{const b=req.body as any;if(b.kind&&b.kind!=='telegram'&&b.kind!=='manual'&&b.enabled)return reply.code(400).send({error:'source_not_automatable'});const r=(await pool.query(`UPDATE aegis.video_sources SET name=COALESCE($2,name),enabled=COALESCE($3,enabled),poll_interval_secs=COALESCE($4,poll_interval_secs) WHERE id=$1 RETURNING id,name,kind,enabled,poll_interval_secs,health`,[(req.params as any).id,b.name,b.enabled,b.pollIntervalSecs])).rows[0];return r??reply.code(404).send({error:'not_found'})});
 app.get('/sightings',{preHandler:[app.requirePerms('video:read')]},async()=>{await raiseVideoAlerts();return{data:(await pool.query(`SELECT s.id,s.fingerprint_id,s.source_id,v.name source,s.url,s.author,s.snippet,s.observed_at,s.matched_via,s.confidence,s.alert_id,s.status FROM aegis.video_sightings s JOIN aegis.video_sources v ON v.id=s.source_id ORDER BY s.observed_at LIMIT 200`)).rows}});
 app.patch('/sightings/:id',{preHandler:[app.requirePerms('video:run')]},async(req,reply)=>{const status=String((req.body as any).status??'');if(!['new','reviewed','false_positive','actioned'].includes(status))return reply.code(400).send({error:'bad_status'});const r=(await pool.query('UPDATE aegis.video_sightings SET status=$2 WHERE id=$1 RETURNING id,status',[(req.params as any).id,status])).rows[0];return r??reply.code(404).send({error:'not_found'})});
 app.post('/sightings',{preHandler:[app.requirePerms('video:run')]},async(req)=>{const b=req.body as any;const snippet=String(b.snippet??'').replace(/[\w.+-]+@[\w.-]+/g,'[redacted-email]').slice(0,240);return(await pool.query(`INSERT INTO aegis.video_sightings(fingerprint_id,source_id,url,author,snippet,observed_at,matched_via,confidence) VALUES($1,$2,$3,$4,$5,COALESCE($6,now()),$7,$8) ON CONFLICT(source_id,url) DO UPDATE SET observed_at=LEAST(aegis.video_sightings.observed_at,EXCLUDED.observed_at) RETURNING id`,[b.fingerprintId,b.sourceId,b.url,b.author,snippet,b.observedAt,b.matchedVia??'manual',b.confidence??1])).rows[0]});
}

async function raiseVideoAlerts():Promise<void>{const pending=(await pool.query(`SELECT s.id,s.url,s.confidence,f.sha256,v.name source FROM aegis.video_sightings s JOIN aegis.video_fingerprints f ON f.id=s.fingerprint_id JOIN aegis.video_sources v ON v.id=s.source_id WHERE s.alert_id IS NULL LIMIT 100`)).rows;for(const s of pending){const r=(await pool.query(`SELECT id FROM aegis.raise_alert(NULL,$1,$2,'high'::aegis.severity,'video','video_sighting',$3,$4,$5::jsonb)`,[`Video sighting: ${s.sha256.slice(0,12)}`,`Registered video observed on ${s.source}.`,s.id,`video:${s.id}`,JSON.stringify({url:s.url,confidence:s.confidence})])).rows[0];if(r?.id)await pool.query('UPDATE aegis.video_sightings SET alert_id=$2 WHERE id=$1',[s.id,r.id]);}}
