apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.fullname" . }}-secrets
  namespace: {{ include "aegis.namespace" . }}
  labels:
    {{- include "aegis.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.db }}"
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  REDIS_URL: "redis://:{{ .Values.redis.password }}@redis:6379/0"
  OPENSEARCH_PASSWORD: {{ .Values.opensearch.password | quote }}
  JWT_ACCESS_SECRET: {{ .Values.secrets.jwtAccessSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
  SEED_ADMIN_PASSWORD: {{ .Values.secrets.seedAdminPassword | quote }}
